package br.ufrj.dcc.mapaviolencia;

public enum CategoriasViolencia {
	HOMICIDIO, 
	ASSALTO, 
	ABUSO_SEXUAL,
	AGRESSAO,
	TRAFICO,
	INCENDIO,
	TIROTEIO,
	FURTO,
	SEMCATEGORIA_CRIMECERTO,
	SEMCATEGORIA_CRIMEINCERTO,
	TODOSOSTOKENS;
}
